version: '2'
services:
    doorman:
        image: xtha/doorman
        links:
          - doormanpostgres
        expose:
            - "5000"
        ports:
            - "0.0.0.0:5000:5000"
        depends_on:
          - doormanpostgres
        environment:
          - DEBUG=true
          - ENV=prod
          - DOORMAN_ENROLL_SECRET=foo
          - DOORMAN_SECRET_KEY=secret-key
          - POSTGRES_USER=doorman
          - POSTGRES_PASSWORD=prprprpr
          - POSTGRES_PORT=doormanpostgres:5432

    doormanpostgres:
        image: postgres:alpine
        volumes:
          - postgresdata:/var/lib/postgresql/data
        expose:
          - 5432
        environment:
          - POSTGRES_USER=doorman
          - POSTGRES_PASSWORD=doorman
volumes:
  postgresdata:
    driver: local
